### ISSUE TITLE
Missing Documentation....

### ISSUE THREAD

**Issue by AnimishY** [Asher-Ul-Haque/Purrfect-Tube-Downloader#1]

**Comment by Asher-Ul-Haque** [comment]
Worry not @AnimishY ,
I will make an extensive readMe file and an extensive Wiki along with video tutorials on downloading and using the app after the endsemesters are over. The app as of 26 November 2023 only takes a URL and downloads the best possible stream that has a good fps and both audio and video in a directory called Downloads.
